# Eska Rock playlista od 2010 r.

In [363]:
import pandas as pd

### Wczytujemy dane

In [364]:
df = pd.read_csv('eska-full.csv')

## Porządkujemy dane

### Nazwy utworów i artystów zamieniamy na małe litery

In [365]:
df['title'] = df['title'].str.lower()
df['artist'] = df['artist'].str.lower()

### Sprawdzamy co się powtarza

In [366]:
duplicates = df.duplicated()

In [367]:
df[duplicates == True].sort_values(by=['date_played','time_played','title','artist'])

,title,artist,date_played,time_played
19474,arahja,kult,2010-10-29,20:50
96627,shotgun,limp bizkit,2011-08-01,01:00
121808,dorosłe dzieci,turbo,2011-10-30,01:00
135791,levitate,hollywood undead,2011-11-21,19:44
135777,alibis,mona,2011-11-23,20:17
139747,monarchy of roses,red hot chili peppers,2011-12-10,17:05
137469,open your eyes,guano apes,2011-12-11,09:07
138585,warszawa,t.love,2011-12-11,13:21
139793,shake it out,florence and the machine,2011-12-14,20:14
136429,another one bites the dust,queen,2011-12-16,00:05
139259,when we stand together,nickelback,2011-12-16,20:10
136476,somebody that i used to know,gotye,2011-12-17,00:19
137255,mein land,rammstein,2011-12-17,10:25
137636,pyro,kings of leon,2011-12-20,13:29
145228,how you remind me,nickelback,2011-12-21,23:32
142466,krew boga,kult,2011-12-24,04:54
142168,piła tango,strachy na lachy,2011-12-28,05:46
143435,pumped up kicks,foster the people,2011-12-28,12:08
141562,noc jak każda inna,happysad,2012-01-01,11:02
142072,damy radę,happysad,2012-01-05,09:27
148256,"nie przeszkadzaj mi, bo tańczę",muchy,2012-01-09,02:34
146638,tonight,seether,2012-01-10,03:46
147936,the catalyst,linkin park,2012-01-12,02:41
152550,satellite,rise against,2012-01-22,12:06
153462,"nie przeszkadzaj mi, bo tańczę",muchy,2012-01-22,20:20
152287,hedonism,skunk anansie,2012-01-24,15:33
152293,the catalyst,linkin park,2012-01-25,12:28
153445,violet hill,coldplay,2012-01-28,23:49
152743,tonight,seether,2012-01-31,20:46
157694,midnight city,m83,2012-02-08,19:37
...,...,...,...,...
909396,w moim ogrodzie,daab,2018-10-28,02:20
909397,w moim ogrodzie,daab,2018-10-28,02:20
909398,w moim ogrodzie,daab,2018-10-28,02:20
909399,w moim ogrodzie,daab,2018-10-28,02:20
909400,w moim ogrodzie,daab,2018-10-28,02:20
909403,trochę wolniej,ira,2018-10-28,02:25
909404,trochę wolniej,ira,2018-10-28,02:25
909334,telefony,republika,2018-10-28,02:28
909335,telefony,republika,2018-10-28,02:28
909336,telefony,republika,2018-10-28,02:28
909408,telefony,republika,2018-10-28,02:29
909409,o! ela,chłopcy z placu broni,2018-10-28,02:33
909411,o! ela,chłopcy z placu broni,2018-10-28,02:33
909331,co może przynieść nowy dzień,kasia kowalska,2018-10-28,02:35
909332,co może przynieść nowy dzień,kasia kowalska,2018-10-28,02:35
909413,co może przynieść nowy dzień,kasia kowalska,2018-10-28,02:35
909416,co może przynieść nowy dzień,kasia kowalska,2018-10-28,02:36
909419,sen o warszawie,czesław niemen,2018-10-28,02:40
909423,sen o warszawie,czesław niemen,2018-10-28,02:40
909421,andzia i ja,oddział zamknięty,2018-10-28,02:43
909422,andzia i ja,oddział zamknięty,2018-10-28,02:43
909424,andzia i ja,oddział zamknięty,2018-10-28,02:43
909429,andzia i ja,oddział zamknięty,2018-10-28,02:44
909427,"dobrze, że cię mam",kortez,2018-10-28,02:46
909430,"dobrze, że cię mam",kortez,2018-10-28,02:46
909433,lipstick on the glass,maanam,2018-10-28,02:49
909434,lipstick on the glass,maanam,2018-10-28,02:49
909435,lipstick on the glass,maanam,2018-10-28,02:49
909437,lipstick on the glass,maanam,2018-10-28,02:50
909442,za ostatni grosz,budka suflera,2018-10-28,02:52

### Usuwamy powtórzenia

In [368]:
df.count()

title          909678
artist         909678
date_played    909678
time_played    909678
dtype: int64

In [369]:
df.drop_duplicates().count()

title          908343
artist         908343
date_played    908343
time_played    908343
dtype: int64

In [370]:
df.drop_duplicates(inplace=True)

### time_played zmieniamy na typ Timestamp

In [372]:
df['datetime'] = df['date_played'] + ' ' + df['time_played']
df['datetime'] = pd.DatetimeIndex(df['datetime'])

### Zmieniamy typ pola date_played z object na datetime24

In [373]:
df['date_played'] = df['date_played'].astype('datetime64')

In [374]:
df.sort_values(by=['datetime']).tail()

,title,artist,date_played,time_played,datetime
909276,wojna,maciek balcar,2018-10-28,23:49,2018-10-28 23:49:00
909291,błyski,hurrockaine,2018-10-28,23:52,2018-10-28 23:52:00
909292,bóg,t.love,2018-10-28,23:55,2018-10-28 23:55:00
909280,wehikuł czasu,dżem,2018-10-28,23:59,2018-10-28 23:59:00
909279,bóg,t.love,2018-10-28,23:59,2018-10-28 23:59:00

In [375]:
df.drop(axis=1, labels='time_played', inplace=True)

In [376]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 908343 entries, 0 to 909677
Data columns (total 4 columns):
title          908343 non-null object
artist         908343 non-null object
date_played    908343 non-null datetime64[ns]
datetime       908343 non-null datetime64[ns]
dtypes: datetime64[ns](2), object(2)
memory usage: 34.7+ MB

## Przechodzimy do analizy dancyh

### Weźmy 50 najczęściej granych zespołów

In [377]:
artists = df['artist']
top_50_artists = artists.value_counts().head(50)
top_50_artists

hey                         17407
myslovitz                   16436
t.love                      15802
perfect                     14773
kult                        14431
u2                          13093
lady pank                   12905
red hot chili peppers       12379
happysad                    12259
queen                       11204
strachy na lachy            10865
maanam                      10735
dżem                        10397
edyta bartosiewicz          10259
linkin park                 10199
republika                    9801
foo fighters                 8122
ira                          7946
coldplay                     7914
o.n.a.                       7846
kings of leon                7726
aerosmith                    7719
oddział zamknięty            7281
ac/dc                        7256
coma                         7117
lipali                       6793
florence and the machine     6529
bon jovi                     6467
lenny kravitz                6383
the rolling stones           6266
metallica                    6248
green day                    6181
muse                         6074
guns n' roses                5981
power of trinity             5948
nirvana                      5807
depeche mode                 5354
nickelback                   5316
dawid podsiadło              5245
pidżama porno                4960
skunk anansie                4959
the doors                    4685
tilt                         4494
led zeppelin                 4426
kazik                        4393
pink floyd                   4350
bob marley                   4337
luxtorpeda                   4326
kasia kowalska               4179
kasabian                     4118
Name: artist, dtype: int64

### Jaki procent odtworzeń wszystkich utworów stanowią utwory czołowych 50 artystów

In [378]:
top_50_artists_percentage_of_all = top_50_artists.sum() / artists.value_counts()[50:].sum() * 100
round(top_50_artists_percentage_of_all, 1)

80.7

### Dla porównania sprawdźmy jaki procent wszystkich zespołów stanowi nasza pięćdziesiątka

In [379]:
top_50_artists_to_number_of_all_artists = top_50_artists.count() / len(artists.unique()) * 100
round(top_50_artists_to_number_of_all_artists, 1)

1.9

### Teraz czas na najczęstrze utwory

In [380]:
titles = df['title']
top_50_titles = titles.value_counts().head(50)
top_50_titles

sen                                    2108
kocham wolność                         1829
syreny                                 1762
biała flaga                            1757
tak tak to ja                          1724
mamona                                 1712
załoga g                               1683
szare miraże                           1667
na pół                                 1660
kryzysowa narzeczona                   1650
whisky                                 1648
chodź ze mną                           1638
nadzieja                               1633
radioactive                            1632
warszawa                               1616
party                                  1612
ona jest ze snu                        1575
drzwi                                  1570
winna                                  1569
kiedy powiem sobie dość                1561
czerwony jak cegła                     1558
chcemy być sobą                        1556
koła czasu                             1551
sic!                                   1550
sing                                   1538
king                                   1527
telefony                               1526
mówię ci że                            1521
polski                                 1518
obudź się                              1516
ten wasz świat                         1502
jedwab                                 1497
scenariusz dla moich sąsiadów          1477
konstytucje                            1468
tatuaż                                 1458
ale w koło jest wesoło                 1458
i nikomu nie wolno się z tego śmiać    1458
spotkanie z ...                        1457
arahja                                 1456
ostatni                                1446
autobiografia                          1438
1996                                   1437
ajrisz                                 1435
nie poganiaj mnie                      1433
wehikuł czasu                          1426
zanim pójdę                            1422
teksański                              1418
jenny                                  1417
oprócz błęktinego nieba                1416
it's my life                           1411
Name: title, dtype: int64

Teraz sprawdźmy kto grał te kawałki

In [381]:
artist_title = df[['artist', 'title']]
top_50_titles.index.values
artist_title[artist_title['title'].isin(top_50_titles.index.values)].drop_duplicates().sort_values(by=['title'])

,artist,title
75492,the wombats,1996
91,t.love,1996
274,t.love,ajrisz
151,perfect,ale w koło jest wesoło
58,kult,arahja
90,perfect,autobiografia
609,republika,biała flaga
10446,lipali,biała flaga
205,perfect,chcemy być sobą
129995,power of trinity,chodź ze mną
275,dżem,czerwony jak cegła
514,o.n.a.,drzwi
512,kobranocka,i nikomu nie wolno się z tego śmiać
1814,bon jovi,it's my life
1392,talk talk,it's my life
168,róże europy,jedwab
208,edyta bartosiewicz,jenny
171,o.n.a.,kiedy powiem sobie dość
294,t.love,king
878899,bartas szymoniak,kocham wolność
133,chłopcy z placu broni,kocham wolność
157,lech janerka,konstytucje
458,o.n.a.,koła czasu
222,lady pank,kryzysowa narzeczona
73,republika,mamona
261,tilt,mówię ci że
106059,coma,na pół
339200,mama selita,na pół
184,ira,nadzieja
585374,maciek balcar,nadzieja
...,...,...
670,oddział zamknięty,party
984,human,polski
363567,within temptation,radioactive
31,kings of leon,radioactive
244653,imagine dragons,radioactive
358,myslovitz,scenariusz dla moich sąsiadów
57398,my riot,sen
19770,edyta bartosiewicz,sen
57,hey,sic!
22781,my chemical romance,sing
1943,travis,sing
386363,ed sheeran,sing
7566,sztywny pal azji,spotkanie z ...
378329,artur rojek,syreny
316,maanam,szare miraże
398,obywatel g.c.,tak tak to ja
305,edyta bartosiewicz,tatuaż
269,hey,teksański
14,republika,telefony
24236,kasia kowalska,telefony
1665,oddział zamknięty,ten wasz świat
10151,kombajn do zbierania kur po wioskach,warszawa
344012,kombajn do zbierania kur po wioska,warszawa
265,t.love,warszawa
406,dżem,wehikuł czasu
107,dżem,whisky
343741,chylinska,winna
1614,agnieszka chylińska,winna
503,happysad,zanim pójdę
746,hurt,załoga g

ups nagla zamiast 50 utworów zrobiło się 67 :)
top_50 utworów trzeba inaczej policzyć

In [382]:
artist_title = df[['artist', 'title']].copy()
artist_title['arti'] = artist_title['artist'] + artist_title['title']
played_times = artist_title['arti'].value_counts()
played_times
played_times_df = played_times.to_frame(name='played_times')
result = pd.merge(left=artist_title, right=played_times_df, how='left', left_on='arti', right_index=True)
result.drop(axis=1, labels='arti', inplace=True)
result.drop_duplicates(inplace=True)
# w pierwszej sześciesiątce nie ma zagranicznych utworów!
result.sort_values(by='played_times', ascending=False).head(50)
result.sort_values(by='played_times', ascending=False).head(120).tail(60)

,artist,title,played_times
568,oddział zamknięty,andzia i ja,1350
164,myslovitz,z twarzą marilyn monroe,1348
371,myslovitz,dla ciebie,1341
70,sztywny pal azji,"wieża radości, wieża samotności",1329
425,t.love,wychowanie,1324
244,edyta bartosiewicz,skłamałam,1322
96,myslovitz,peggy brown,1313
1030,myslovitz,długość dźwięku samotności,1311
1231,voo voo,nim stanie się tak,1304
163,coma,daleka droga do domu,1297
6,myslovitz,sprzedawcy marzeń,1287
179,coma,spadam,1278
1255,edyta bartosiewicz,szał,1278
768,hey,cisza ja i czas,1274
247,turbo,dorosłe dzieci,1267
696,kazik,celina,1265
1904,o.n.a.,znalazłam,1262
266,myslovitz,chłopcy,1257
264144,bastille,things we lost in the fire,1256
328323,hozier,take me to church,1254
154,maanam,cykady na cykladach,1252
29491,kult,mieszkam w polsce,1252
6059,republika,sexy doll,1251
457,brygada kryzys,to co czujesz,1242
46,maanam,raz dwa raz dwa,1234
1071,ac/dc,highway to hell,1232
64,perfect,lokomotywa z ogłoszenia,1226
161,hey,zazdrość,1225
1246,happysad,noc jak każda inna,1210
506,ira,mój bóg,1208
912,the clash,should i stay or should i go,1193
60,pidżama porno,bal u senatora,1193
40,steppenwolf,born to be wild,1186
98,t.love,autobusy i tramwaje,1181
1617,happysad,damy radę,1181
51597,foster the people,pumped up kicks,1178
65,myslovitz,acidland,1176
85,kult,hej czy nie wiecie,1176
349,klaus mitffoch,jezu jak się cieszę,1165
412,tsa,51,1164
125,tilt,runął już ostatni mur,1161
57398,my riot,sen,1160
174686,luxtorpeda,hymn,1155
534,nirvana,smells like teen spirit,1144
115,pidżama porno,ezoteryczny poznań,1138
114366,florence and the machine,shake it out,1136
1264,joan jett,i love rock and roll,1132
1112,bon jovi,livin' on a prayer,1130
2091,happysad,milowy las,1126
6062,perfect,"wyspa, drzewo, zamek",1125
185630,lady pank,wciąż bardziej obcy,1124
293092,lipali,popioły,1120
1285,hey,kto tam? kto jest w środku?,1115
96257,ira,pare chwil,1111
1010,kult,dziewczyna bez zęba na przedzie,1102
55,republika,odchodząc,1101
631,strachy na lachy,twoje oczy lubią mnie,1094
1814,bon jovi,it's my life,1081
1123,lynyrd skynyrd,sweet home alabama,1079
1367,midnight oil,beds are burning,1074

In [387]:
"Dataset zawiera dane o utworach zagranych od %s do %s. W sumie ok. %s odtworzeń" % (min(df['datetime']), max(df['datetime']), len(df))

'Dataset zawiera dane o utworach zagranych od 2010-09-01 00:04:00 do 2018-10-28 23:59:00. W sumie ok. 908343 odtworzeń'

ile utworów średnio dziennie jest granych

In [395]:
df.groupby('date_played').count().mean()

title       305.325378
artist      305.325378
datetime    305.325378
dtype: float64

In [396]:
df[df['date_played'] >= '2018-01-01'].groupby('artist').count().sort_values(by='title', ascending=False)

                                     title  date_played  datetime
artist
perfect                               1914         1914      1914
t.love                                1911         1911      1911
hey                                   1868         1868      1868
kult                                  1620         1620      1620
lady pank                             1599         1599      1599
myslovitz                             1592         1592      1592
queen                                 1459         1459      1459
u2                                    1438         1438      1438
dawid podsiadło                       1428         1428      1428
dżem                                  1386         1386      1386
maanam                                1363         1363      1363
greta van fleet                       1273         1273      1273
strachy na lachy                      1258         1258      1258
republika                             1185         1185      1185
edyta bartosiewicz                    1133         1133      1133
lenny kravitz                         1120         1120      1120
happysad                              1098         1098      1098
guns n' roses                         1045         1045      1045
red hot chili peppers                 1044         1044      1044
imagine dragons                       1009         1009      1009
aerosmith                             1003         1003      1003
power of trinity                       957          957       957
linkin park                            950          950       950
o.n.a.                                 926          926       926
ac/dc                                  900          900       900
kazik                                  893          893       893
bon jovi                               889          889       889
muse                                   868          868       868
florence and the machine               856          856       856
green day                              774          774       774
...                                    ...          ...       ...
simon & garfunkel                        3            3         3
the smiths                               2            2         2
meskie granie orkiestra 2018/kortez      2            2         2
neil young                               2            2         2
asia                                     2            2         2
kylie minogue                            2            2         2
nick cave                                2            2         2
rage against the machine                 2            2         2
dexy's midnight runners                  1            1         1
emerson, lake & palmer                   1            1         1
starship                                 1            1         1
electric light orchestra                 1            1         1
the blues brothers band                  1            1         1
supertramp                               1            1         1
sinéad o'connor                          1            1         1
bad company                              1            1         1
the moody blues                          1            1         1
emf                                      1            1         1
morrissey                                1            1         1
frank zappa                              1            1         1
monty python                             1            1         1
glenn frey                               1            1         1
robert palmer                            1            1         1
hootie and the blowfish                  1            1         1
john lee hooker/carlos santana           1            1         1
usa for africa                           1            1         1
phil collins                             1            1         1
larry mullen                             1            1         1
leonard cohen                            1            1         1
george harrison                          1            1         1

[413 rows x 3 columns]

In [412]:
most_popular_artists_2018 = df[df['date_played'] >= '2018-01-01'].groupby('artist').count().sort_values(by='title', ascending=False)

In [413]:
most_popular_artists_2018 = most_popular_artists_2018.drop(columns=['title', 'date_played'])

In [416]:
most_popular_artists_2018.columns = ['played_times']

In [418]:
most_popular_artists_2018

                                     played_times
artist
perfect                                      1914
t.love                                       1911
hey                                          1868
kult                                         1620
lady pank                                    1599
myslovitz                                    1592
queen                                        1459
u2                                           1438
dawid podsiadło                              1428
dżem                                         1386
maanam                                       1363
greta van fleet                              1273
strachy na lachy                             1258
republika                                    1185
edyta bartosiewicz                           1133
lenny kravitz                                1120
happysad                                     1098
guns n' roses                                1045
red hot chili peppers                        1044
imagine dragons                              1009
aerosmith                                    1003
power of trinity                              957
linkin park                                   950
o.n.a.                                        926
ac/dc                                         900
kazik                                         893
bon jovi                                      889
muse                                          868
florence and the machine                      856
green day                                     774
...                                           ...
simon & garfunkel                               3
the smiths                                      2
meskie granie orkiestra 2018/kortez             2
neil young                                      2
asia                                            2
kylie minogue                                   2
nick cave                                       2
rage against the machine                        2
dexy's midnight runners                         1
emerson, lake & palmer                          1
starship                                        1
electric light orchestra                        1
the blues brothers band                         1
supertramp                                      1
sinéad o'connor                                 1
bad company                                     1
the moody blues                                 1
emf                                             1
morrissey                                       1
frank zappa                                     1
monty python                                    1
glenn frey                                      1
robert palmer                                   1
hootie and the blowfish                         1
john lee hooker/carlos santana                  1
usa for africa                                  1
phil collins                                    1
larry mullen                                    1
leonard cohen                                   1
george harrison                                 1

[413 rows x 1 columns]

Sprawdźmy teraz kiedy zaczęto grać małomiasteczkowego, ile razy go zagrano, jaka była częstotliwość w rozbiciu na dnie

In [432]:
df_2018 = df[df['date_played'] >= '2018-01-01']

title          92619
artist         92619
date_played    92619
datetime       92619
dtype: int64

In [450]:
first_time = min(df_2018[df_2018['title'] == 'małomiasteczkowy']['datetime'])
first_time

Timestamp('2018-06-10 02:33:00')

In [451]:
last_time = max(df_2018[df_2018['title'] == 'małomiasteczkowy']['datetime'])
last_time

Timestamp('2018-10-19 05:50:00')

In [434]:
times_played = len(df_2018[df_2018['title'] == 'małomiasteczkowy'])

In [452]:
times_played

480

In [445]:
df_malomiasteczkowy_times_played = df_2018[df_2018['title'] == 'małomiasteczkowy'].groupby('date_played').count()
df_malomiasteczkowy_times_played = df_malomiasteczkowy_times_played.drop(columns=['title', 'artist'])
df_malomiasteczkowy_times_played.columns = ['times_played']

In [449]:
df_malomiasteczkowy_times_played.sort_values(by=['times_played'], ascending=False)

             times_played
date_played
2018-08-07              9
2018-08-05              8
2018-08-09              8
2018-08-16              8
2018-08-13              8
2018-08-17              8
2018-08-18              8
2018-08-12              8
2018-08-10              8
2018-08-19              8
2018-08-15              8
2018-08-20              8
2018-08-21              8
2018-08-22              8
2018-08-08              8
2018-08-23              8
2018-08-06              8
2018-08-14              8
2018-08-11              7
2018-06-20              7
2018-06-29              6
2018-08-04              6
2018-07-26              6
2018-07-25              6
2018-07-24              6
2018-07-29              6
2018-07-30              6
2018-07-21              6
2018-07-31              6
2018-08-01              6
...                   ...
2018-09-18              2
2018-10-10              2
2018-10-03              1
2018-10-06              1
2018-10-07              1
2018-10-09              1
2018-10-17              1
2018-10-12              1
2018-10-13              1
2018-10-14              1
2018-10-16              1
2018-10-18              1
2018-09-30              1
2018-10-02              1
2018-09-10              1
2018-09-29              1
2018-09-28              1
2018-09-26              1
2018-09-25              1
2018-09-23              1
2018-09-22              1
2018-09-21              1
2018-09-19              1
2018-09-16              1
2018-09-14              1
2018-09-13              1
2018-09-12              1
2018-09-08              1
2018-09-07              1
2018-10-19              1

[109 rows x 1 columns]